spring:
  application:
    name: ssarain
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:develop}
  mail:
    host: smtp.naver.com
    port: 587
    username: ${SMTP_EMAIL}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    issuer: ssarain
    access-token-secret: ${JWT_ACCESS_SECRET}
    refresh-token-secret: ${JWT_REFRESH_SECRET}
    access-token-expiration-seconds: 3600
    refresh-token-expiration-seconds: 1209600
  cors:
    allowed-methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    allowed-headers:
      - "*"
    exposed-headers:
      - Authorization